const houseNames = [
  'Gryffindor',
  'Hufflepuff',
  'Ravenclaw',
  'Slytherin',
]

const crestImgs = [
  'images/0.31_Gryffindor_Crest_Transparent.png',
  'images/0.51_Hufflepuff_Crest_Transparent.png',
  'images/0.41_Ravenclaw_Crest_Transparent.png',
  'images/0.61_Slytherin_Crest_Transparent.png',
]

const gryffindor = [
  'Godric Gryffindor',
  'bravery',
  'daring',
  'nerve',
  'chivalry',
  'determination',
  'lion',
  'scarlet and gold',
  'Minerva McGonagall',
  'The Fat Lady',
  'Nearly Headless Nick',
  'fire',
  'Albus Dumbledore',
  'Sirius Black',
  'Harry Potter',
  'Hermione Granger',
  'Sword of Gryffindor',
  'wingardium leviosa',
  'apparate',
  'Auror',
  'Goblet of Fire',
  'Sorcerer\'s Stone',
  'golden snitch',
  'Marauder\'s Map',
  'parselmouth',
  'parseltongue',
  'Rubeus Hagrid',
  'James and Lily',
];

const hufflepuff = [
  'Helga Hufflepuff',
  'hard-working',
  'dedication',
  'patience',
  'loyalty',
  'fair play',
  'friendly',
  'honest',
  'impartial',
  'badger',
  'yellow and black',
  'Pomona Sprout',
  'The Fat Friar',
  'earth',
  'Newt Scamander',
  'Cedric Diggory',
  'gillyweed',
  'stupefy',
  'lumos',
  'confundo',
  'mandrake',
  'The Quibbler',
  'Whomping Willow',
  'Nymphadora Tonks',
];

const ravenclaw = [
  'Rowena Ravenclaw',
  'intelligence',
  'knowledge',
  'wit',
  'learning',
  'wisdom',
  'intellect',
  'eagle',
  'blue and bronze',
  'Filius Flitwick',
  'The Grey Lady',
  'air',
  'Gilderoy Lockhart',
  'Luna Lovegood',
  'Cho Chang',
  'pure-blood',
  'expecto patronum',
  'expelliarmus',
  'alohomora',
  'quidditch',
  'merpeople',
  'Ollivander',
];

const slytherin = [
  'Salazar Slytherin',
  'ambition',
  'cunning',
  'resourcefulness',
  'shrewd',
  'clever',
  'serpent',
  'snake',
  'green and silver',
  'Horace Slughorn',
  'Severus Snape',
  'The Bloody Baron',
  'water',
  'Draco Malfoy',
  'Crabbe',
  'Goyle',
  'Tom Riddle',
  'Voldemort',
  'He Who Must Not Be Named',
  'crucio',
  'avada kedavra',
  'nox',
  'Azkaban',
  'Basilisk',
  'The Dark Mark',
  'Death Eater',
  'Dementor',
  'Dolores Umbridge',
];
